#!/usr/bin/with-contenv bash

export XCURSOR_THEME=breeze

# Default sink setup
if [ ! -f '/dev/shm/audio.lock' ]; then
  until [ -f /defaults/pid ]; do
    sleep .5
  done
  s6-setuidgid abc with-contenv pactl \
    load-module module-null-sink \
    sink_name="output" \
    sink_properties=device.description="output"
  s6-setuidgid abc with-contenv pactl \
    load-module module-null-sink \
    sink_name="input" \
    sink_properties=device.description="input"
  touch /dev/shm/audio.lock
fi

# Start Selkies with shared session + locked 1080p resolution
exec s6-setuidgid abc \
  selkies \
    --addr="localhost" \
    --mode="websockets" \
    --enable-shared=true \
    --is-manual-resolution-mode=true \
    --manual-width=1920 \
    --manual-height=1080
